"""
src/reporting.py
Markdown and HTML report generation for ThreatLens-Kali.
"""

from pathlib import Path
from datetime import datetime
from jinja2 import Template


def write_markdown_report(
    output_dir,
    input_file,
    iocs,
    detections,
    timestamp=None
):
    """Generate a Markdown investigation report.
    
    Args:
        output_dir: Directory for the output report
        input_file: Path to the analyzed input file
        iocs: Dictionary of extracted IOCs
        detections: List of detection results
        timestamp: Optional timestamp for report naming
        
    Returns:
        str: Path to the generated report
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    report_file = output_path / f"report_{timestamp}.md"
    
    lines = []
    lines.append("# ThreatLens-Kali Investigation Report")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Source:** {input_file}")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Executive Summary
    high_count = sum(1 for d in detections if d.get('severity') == 'high')
    critical_count = sum(1 for d in detections if d.get('severity') == 'critical')
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"- **Total IOCs Found:** {sum(len(v) for v in iocs.values())}")
    lines.append(f"- **Total Detections:** {len(detections)}")
    lines.append(f"- **High Severity:** {high_count}")
    lines.append(f"- **Critical Severity:** {critical_count}")
    lines.append("")
    
    if critical_count > 0 or high_count > 0:
        lines.append("> :warning: **IMMEDIATE ATTENTION REQUIRED** - High/Critical severity detections found.")
        lines.append("")
    
    # IOCs
    lines.append("## Indicators of Compromise (IOCs)")
    lines.append("")
    
    for category, values in iocs.items():
        lines.append(f"### {category.upper()}")
        if values:
            for item in values[:20]:
                lines.append(f"- `{item}`")
            if len(values) > 20:
                lines.append(f"- ... and {len(values) - 20} more")
        else:
            lines.append("- None found")
        lines.append("")
    
    # Detections
    lines.append("## Detection Results")
    lines.append("")
    
    if detections:
        lines.append("| Severity | Rule | MITRE ATT&CK | Description |")
        lines.append("|----------|------|--------------|-------------|")
        for det in sorted(detections, key=lambda x: {'critical': 4, 'high': 3, 'medium': 2, 'low': 1, 'info': 0}.get(x.get('severity', 'info'), 0), reverse=True):
            severity = det.get('severity', 'info').upper()
            rule = det.get('rule', 'Unknown')
            mitre = det.get('mitre', '-')
            desc = det.get('description', '-')
            lines.append(f"| {severity} | {rule} | {mitre} | {desc} |")
    else:
        lines.append("No detections triggered.")
    
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by ThreatLens-Kali | [gauravmalhotra3300-hub/threatlens-kali](https://github.com/gauravmalhotra3300-hub/threatlens-kali)*")
    
    report_file.write_text("\n".join(lines), encoding="utf-8")
    return str(report_file)


def write_html_report(
    output_dir,
    input_file,
    iocs,
    detections,
    timestamp=None
):
    """Generate an HTML investigation report.
    
    Args:
        output_dir: Directory for the output report
        input_file: Path to the analyzed input file
        iocs: Dictionary of extracted IOCs
        detections: List of detection results
        timestamp: Optional timestamp for report naming
        
    Returns:
        str: Path to the generated report
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    report_file = output_path / f"report_{timestamp}.html"
    
    html_template = Template("""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ThreatLens-Kali Investigation Report</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }
        h1 { color: #1a1a2e; border-bottom: 2px solid #16213e; }
        h2 { color: #0f3460; }
        .severity-critical { color: #e94560; font-weight: bold; }
        .severity-high { color: #ff6b6b; font-weight: bold; }
        .severity-medium { color: #feca57; font-weight: bold; }
        .severity-low { color: #48dbfb; }
        table { border-collapse: collapse; width: 100%; margin: 10px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #16213e; color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .alert { background-color: #ffdddd; border-left: 4px solid #e94560; padding: 10px; margin: 10px 0; }
        .meta { color: #666; font-size: 0.9em; }
        code { background-color: #f4f4f4; padding: 2px 5px; border-radius: 3px; }
    </style>
</head>
<body>
    <h1>ThreatLens-Kali Investigation Report</h1>
    <p class="meta"><strong>Generated:</strong> {{ gen_time }} | <strong>Source:</strong> {{ input_file }}</p>
    
    <h2>Executive Summary</h2>
    <p><strong>Total IOCs:</strong> {{ ioc_count }} | <strong>Detections:</strong> {{ det_count }} | <strong>High/Critical:</strong> {{ high_count }}</p>
    {% if high_count > 0 %}
    <div class="alert">WARNING: High/Critical severity detections require immediate attention!</div>
    {% endif %}
    
    <h2>Indicators of Compromise</h2>
    {% for cat, vals in iocs.items() %}
    <h3>{{ cat|upper }}</h3>
    {% if vals %}
    <ul>
    {% for v in vals[:15] %}<li><code>{{ v }}</code></li>{% endfor %}
    {% if vals|length > 15 %}<li>... and {{ vals|length - 15 }} more</li>{% endif %}
    </ul>
    {% else %}<p>None found</p>{% endif %}
    {% endfor %}
    
    <h2>Detection Results</h2>
    {% if detections %}
    <table>
        <tr><th>Severity</th><th>Rule</th><th>MITRE ATT&CK</th><th>Description</th></tr>
        {% for d in detections %}
        <tr>
            <td class="severity-{{ d.severity|lower }}">{{ d.severity|upper }}</td>
            <td>{{ d.rule }}</td>
            <td>{{ d.mitre or '-' }}</td>
            <td>{{ d.description or '-' }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}<p>No detections triggered.</p>{% endif %}
    
    <hr>
    <p class="meta"><em>Generated by ThreatLens-Kali | <a href="https://github.com/gauravmalhotra3300-hub/threatlens-kali">gauravmalhotra3300-hub/threatlens-kali</a></em></p>
</body>
</html>""")
    
    html_content = html_template.render(
        gen_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        input_file=input_file,
        iocs=iocs,
        ioc_count=sum(len(v) for v in iocs.values()),
        det_count=len(detections),
        high_count=sum(1 for d in detections if d.get('severity') in ['high', 'critical']),
        detections=detections
    )
    
    report_file.write_text(html_content, encoding="utf-8")
    return str(report_file)
